### ISSUE TITLE
Can't update to 11.12.0-44

### ISSUE THREAD

**Issue by leeshey** [zoogie/b9sTool#10]
Hi, I'm at South Korea here, I can't update to 11.12.0-44 (because the lastest update in Korea is 11.12.0-38K). So should I wait for update for 11.12.0-44K? Or use your 11.12.0-44 b9s?

**Comment by aspargas2** [comment]
The number after the dash is irrelevant to the native firm version, so using current b9stool is safe on your current firmware.
